export const SEEDS = [
  // ─── TECH / DEV ───────────────────────────────────────────────────────────
  {
    label: 'Hacker News',
    url: 'https://news.ycombinator.com',
    feedUrl: 'https://news.ycombinator.com/rss',
    description: 'The canonical aggregator for startup founders, engineers, and anyone who ships things.',
    tags: ['tech', 'dev', 'news'],
    quality: 3,
  },
  {
    label: 'lobste.rs',
    url: 'https://lobste.rs',
    feedUrl: 'https://lobste.rs/rss',
    description: 'Invite-only link aggregator with unusually high signal-to-noise for systems programmers.',
    tags: ['dev', 'tech', 'oss'],
    quality: 3,
  },
  {
    label: 'The Verge',
    url: 'https://www.theverge.com',
    feedUrl: 'https://www.theverge.com/rss/index.xml',
    description: 'Consumer tech news with strong culture coverage and above-average writing.',
    tags: ['tech', 'news'],
    quality: 2,
  },
  {
    label: 'Wired',
    url: 'https://www.wired.com',
    feedUrl: 'https://www.wired.com/feed/rss',
    description: 'Long-form tech journalism at the intersection of culture, business, and science.',
    tags: ['tech', 'news', 'science'],
    quality: 2,
  },
  {
    label: 'Ars Technica',
    url: 'https://arstechnica.com',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/index',
    description: 'Deep-dive tech reporting written for readers who actually understand the subject.',
    tags: ['tech', 'science', 'news'],
    quality: 3,
  },
  {
    label: 'TechCrunch',
    url: 'https://techcrunch.com',
    feedUrl: 'https://techcrunch.com/feed/',
    description: 'Startup and venture news, fastest breaking coverage of funding rounds and launches.',
    tags: ['tech', 'business', 'news'],
    quality: 2,
  },
  {
    label: 'MIT Technology Review',
    url: 'https://www.technologyreview.com',
    feedUrl: 'https://www.technologyreview.com/feed/',
    description: 'Authoritative, peer-adjacent coverage of emerging technology and its societal stakes.',
    tags: ['tech', 'science', 'ai'],
    quality: 3,
  },
  {
    label: 'ACM Queue',
    url: 'https://queue.acm.org',
    feedUrl: 'https://queue.acm.org/rss/feeds/queuecontent.xml',
    description: 'Practitioner-focused engineering articles from the Association for Computing Machinery.',
    tags: ['dev', 'tech'],
    quality: 3,
  },
  {
    label: 'InfoQ',
    url: 'https://www.infoq.com',
    feedUrl: 'https://feed.infoq.com',
    description: 'Conference talks and articles on software architecture, cloud, and enterprise engineering.',
    tags: ['dev', 'tech'],
    quality: 2,
  },
  {
    label: 'The Register',
    url: 'https://www.theregister.com',
    feedUrl: 'https://www.theregister.com/headlines.atom',
    description: 'Sardonic British tech reporting — enterprise, cloud, and security with genuine wit.',
    tags: ['tech', 'news', 'security'],
    quality: 2,
  },
  {
    label: 'Changelog',
    url: 'https://changelog.com',
    feedUrl: 'https://changelog.com/feed',
    description: 'Podcast network and blog at the pulse of open-source software and developer culture.',
    tags: ['dev', 'oss', 'news'],
    quality: 2,
  },
  {
    label: 'CSS-Tricks',
    url: 'https://css-tricks.com',
    feedUrl: 'https://css-tricks.com/feed/',
    description: 'The go-to reference for CSS techniques, front-end patterns, and web platform news.',
    tags: ['web', 'dev', 'design'],
    quality: 2,
  },
  {
    label: 'Smashing Magazine',
    url: 'https://www.smashingmagazine.com',
    feedUrl: 'https://www.smashingmagazine.com/feed/',
    description: 'High-quality tutorials and articles for web designers and front-end developers.',
    tags: ['web', 'design', 'dev'],
    quality: 2,
  },
  {
    label: 'web.dev Blog',
    url: 'https://web.dev',
    feedUrl: 'https://web.dev/feed.xml',
    description: "Google's authoritative guide to modern web development best practices and APIs.",
    tags: ['web', 'dev'],
    quality: 3,
  },
  {
    label: 'V8 Blog',
    url: 'https://v8.dev',
    feedUrl: 'https://v8.dev/blog.atom',
    description: "Primary source for JavaScript engine internals, performance, and new language features from Chrome's V8 team.",
    tags: ['dev', 'web'],
    quality: 3,
  },
  {
    label: 'WebKit Blog',
    url: 'https://webkit.org/blog',
    feedUrl: 'https://webkit.org/feed/',
    description: "Apple's WebKit team on new web platform features, performance work, and standards.",
    tags: ['web', 'dev'],
    quality: 3,
  },
  {
    label: 'Mozilla Hacks',
    url: 'https://hacks.mozilla.org',
    feedUrl: 'https://hacks.mozilla.org/feed/',
    description: 'Deep technical posts from Mozilla engineers on Firefox, Rust, and the open web.',
    tags: ['web', 'dev', 'oss'],
    quality: 2,
  },
  {
    label: 'GitHub Blog',
    url: 'https://github.blog',
    feedUrl: 'https://github.blog/feed/',
    description: 'Product announcements, engineering deep-dives, and developer research from GitHub.',
    tags: ['dev', 'oss', 'tech'],
    quality: 2,
  },
  {
    label: 'GitLab Blog',
    url: 'https://about.gitlab.com/blog',
    feedUrl: 'https://about.gitlab.com/atom.xml',
    description: 'DevOps, CI/CD, and remote-work culture from the all-remote software company.',
    tags: ['dev', 'oss'],
    quality: 2,
  },
  {
    label: 'Netlify Blog',
    url: 'https://www.netlify.com/blog',
    feedUrl: 'https://www.netlify.com/blog/index.xml',
    description: 'JAMstack patterns, edge computing, and DX improvements from the deployment platform.',
    tags: ['web', 'dev'],
    quality: 2,
  },
  {
    label: 'Vercel Blog',
    url: 'https://vercel.com/blog',
    feedUrl: 'https://vercel.com/atom',
    description: 'Next.js releases, edge runtime news, and front-end performance insights.',
    tags: ['web', 'dev'],
    quality: 2,
  },
  {
    label: 'Cloudflare Blog',
    url: 'https://blog.cloudflare.com',
    feedUrl: 'https://blog.cloudflare.com/rss/',
    description: 'Network engineering, DDoS research, and product launches from the internet infrastructure company.',
    tags: ['tech', 'security', 'dev'],
    quality: 3,
  },
  {
    label: 'Stack Overflow Blog',
    url: 'https://stackoverflow.blog',
    feedUrl: 'https://stackoverflow.blog/feed/',
    description: 'Developer survey data, engineering culture, and programming language trends.',
    tags: ['dev', 'tech'],
    quality: 2,
  },
  {
    label: 'Joel on Software',
    url: 'https://www.joelonsoftware.com',
    feedUrl: 'https://www.joelonsoftware.com/feed/',
    description: 'Classic software management and engineering essays that shaped a generation of developers.',
    tags: ['dev', 'productivity'],
    quality: 3,
  },
  {
    label: 'Paul Graham Essays',
    url: 'https://paulgraham.com',
    feedUrl: 'https://paulgraham.com/rss.html',
    description: 'Influential essays on startups, programming, and how to think from the YC co-founder.',
    tags: ['tech', 'business', 'dev'],
    quality: 3,
  },
  {
    label: 'Signal v. Noise',
    url: 'https://signalvnoise.com',
    feedUrl: 'https://m.signalvnoise.com/feed/',
    description: 'Basecamp on product design, company culture, and sustainable software businesses.',
    tags: ['dev', 'business', 'design'],
    quality: 2,
  },
  {
    label: 'Martin Fowler',
    url: 'https://martinfowler.com',
    feedUrl: 'https://martinfowler.com/feed.atom',
    description: 'The definitive voice on software architecture, refactoring, and agile engineering practices.',
    tags: ['dev', 'tech'],
    quality: 3,
  },
  {
    label: 'The Pragmatic Engineer',
    url: 'https://newsletter.pragmaticengineer.com',
    feedUrl: 'https://newsletter.pragmaticengineer.com/feed',
    description: "Gergely Orosz's reporting on Big Tech engineering culture, compensation, and career growth.",
    tags: ['dev', 'business'],
    quality: 3,
  },
  {
    label: "Lenny's Newsletter",
    url: 'https://www.lennysnewsletter.com',
    feedUrl: 'https://www.lennysnewsletter.com/feed',
    description: 'Product management and growth tactics from a former Airbnb PM — practical and data-driven.',
    tags: ['business', 'productivity'],
    quality: 2,
  },
  {
    label: 'Engineering at Meta',
    url: 'https://engineering.fb.com',
    feedUrl: 'https://engineering.fb.com/feed/',
    description: 'Infrastructure at massive scale: React internals, data systems, and AI tooling from Meta.',
    tags: ['dev', 'tech', 'ai'],
    quality: 2,
  },
  {
    label: 'Netflix Tech Blog',
    url: 'https://netflixtechblog.com',
    feedUrl: 'https://netflixtechblog.com/feed',
    description: 'Streaming infrastructure, A/B testing, and recommendation systems at Netflix scale.',
    tags: ['dev', 'tech'],
    quality: 3,
  },
  {
    label: 'Uber Engineering',
    url: 'https://www.uber.com/en-US/blog/engineering/',
    feedUrl: 'https://www.uber.com/en-US/blog/engineering/rss/',
    description: 'Real-time systems, geospatial algorithms, and distributed infrastructure from Uber.',
    tags: ['dev', 'tech'],
    quality: 2,
  },
  {
    label: 'Dropbox Tech',
    url: 'https://dropbox.tech',
    feedUrl: 'https://dropbox.tech/feed',
    description: 'Sync algorithms, storage engineering, and ML applications from the Dropbox team.',
    tags: ['dev', 'tech'],
    quality: 2,
  },
  {
    label: 'Airbnb Tech',
    url: 'https://medium.com/airbnb-engineering',
    feedUrl: 'https://medium.com/feed/airbnb-engineering',
    description: 'Search ranking, trust systems, and design infrastructure from Airbnb engineering.',
    tags: ['dev', 'tech', 'design'],
    quality: 2,
  },
  {
    label: 'Spotify Engineering',
    url: 'https://engineering.atspotify.com',
    feedUrl: 'https://engineering.atspotify.com/feed/',
    description: 'Audio infrastructure, ML personalization, and developer tooling from Spotify.',
    tags: ['dev', 'tech'],
    quality: 2,
  },
  {
    label: 'Stripe Blog',
    url: 'https://stripe.com/blog',
    feedUrl: 'https://stripe.com/blog/feed.rss',
    description: 'Payments infrastructure, developer experience, and economic research from Stripe.',
    tags: ['dev', 'business', 'finance'],
    quality: 3,
  },
  {
    label: 'Twilio Blog',
    url: 'https://www.twilio.com/en-us/blog',
    feedUrl: 'https://www.twilio.com/en-us/blog/rss',
    description: 'Communications APIs, developer tutorials, and CPaaS product news from Twilio.',
    tags: ['dev', 'tech'],
    quality: 1,
  },
  {
    label: 'Auth0 Blog',
    url: 'https://auth0.com/blog',
    feedUrl: 'https://auth0.com/blog/rss.xml',
    description: 'Identity, authentication patterns, and security best practices for developers.',
    tags: ['dev', 'security'],
    quality: 2,
  },
  {
    label: 'DigitalOcean Community',
    url: 'https://www.digitalocean.com/community',
    feedUrl: 'https://www.digitalocean.com/community/articles/feed',
    description: 'Practical DevOps and Linux tutorials aimed at developers running their own infrastructure.',
    tags: ['dev', 'linux', 'tech'],
    quality: 1,
  },
  {
    label: 'DEV Community',
    url: 'https://dev.to',
    feedUrl: 'https://dev.to/feed',
    description: 'Open community blog with a high volume of practitioner posts across every stack.',
    tags: ['dev', 'web'],
    quality: 1,
  },
  {
    label: 'Hashnode',
    url: 'https://hashnode.com',
    feedUrl: 'https://hashnode.com/community/feed.rss',
    description: 'Developer-owned blogs on a federated platform — good for niche deep-dives.',
    tags: ['dev', 'web'],
    quality: 1,
  },
  {
    label: 'Codrops',
    url: 'https://tympanus.net/codrops',
    feedUrl: 'https://tympanus.net/codrops/feed/',
    description: 'Creative front-end experiments and polished UI tutorials pushing what browsers can do.',
    tags: ['web', 'design', 'dev'],
    quality: 2,
  },
  {
    label: 'Bytes.dev',
    url: 'https://bytes.dev',
    feedUrl: 'https://bytes.dev/rss.xml',
    description: 'Witty weekly newsletter covering the JavaScript ecosystem with genuine editorial voice.',
    tags: ['dev', 'web'],
    quality: 2,
  },
  {
    label: 'JavaScript Weekly',
    url: 'https://javascriptweekly.com',
    feedUrl: 'https://javascriptweekly.com/rss/1a1a0847',
    description: 'The most reliable weekly digest of JavaScript news, articles, and new libraries.',
    tags: ['dev', 'web'],
    quality: 2,
  },
  {
    label: 'Node Weekly',
    url: 'https://nodeweekly.com',
    feedUrl: 'https://nodeweekly.com/rss/1a1a0847',
    description: 'Curated weekly roundup of Node.js releases, tutorials, and ecosystem news.',
    tags: ['dev', 'web'],
    quality: 2,
  },
  {
    label: 'Python Weekly',
    url: 'https://www.pythonweekly.com',
    feedUrl: 'https://feeds.feedburner.com/PythonWeekly',
    description: 'Weekly Python news, packages, and tutorials spanning data science to web frameworks.',
    tags: ['dev'],
    quality: 2,
  },
  {
    label: 'Go Weekly',
    url: 'https://golangweekly.com',
    feedUrl: 'https://golangweekly.com/rss/1a1a0847',
    description: 'The authoritative weekly digest for Go developers — releases, articles, and projects.',
    tags: ['dev'],
    quality: 2,
  },
  {
    label: 'Rust Blog',
    url: 'https://blog.rust-lang.org',
    feedUrl: 'https://blog.rust-lang.org/feed.xml',
    description: 'Official Rust language releases, RFC announcements, and edition planning from the core team.',
    tags: ['dev', 'oss'],
    quality: 3,
  },
  {
    label: 'Swift by Sundell',
    url: 'https://www.swiftbysundell.com',
    feedUrl: 'https://www.swiftbysundell.com/feed.rss',
    description: 'High-quality Swift tutorials and API design articles for Apple platform developers.',
    tags: ['dev', 'mobile'],
    quality: 2,
  },
  {
    label: 'Kotlin Blog',
    url: 'https://blog.jetbrains.com/kotlin',
    feedUrl: 'https://blog.jetbrains.com/kotlin/feed/',
    description: 'Official Kotlin language releases, new features, and ecosystem news from JetBrains.',
    tags: ['dev', 'mobile'],
    quality: 2,
  },
  {
    label: 'Increment',
    url: 'https://increment.com',
    feedUrl: 'https://increment.com/feed.xml',
    description: "Stripe's thoughtful magazine on software engineering practices and team culture.",
    tags: ['dev', 'tech'],
    quality: 3,
  },
  {
    label: 'The Morning Paper',
    url: 'https://blog.acolyer.org',
    feedUrl: 'https://blog.acolyer.org/feed/',
    description: 'Accessible summaries of important CS research papers for working engineers.',
    tags: ['dev', 'tech', 'ai'],
    quality: 3,
  },
  {
    label: 'High Scalability',
    url: 'http://highscalability.com',
    feedUrl: 'http://feeds.feedburner.com/HighScalability',
    description: 'Architecture teardowns and lessons from companies that have scaled to millions of users.',
    tags: ['dev', 'tech'],
    quality: 2,
  },
  {
    label: 'Troy Hunt Blog',
    url: 'https://www.troyhunt.com',
    feedUrl: 'https://feeds.feedburner.com/TroyHunt',
    description: 'Web security, data breaches, and responsible disclosure from the creator of HaveIBeenPwned.',
    tags: ['security', 'dev'],
    quality: 3,
  },
  {
    label: 'Coding Horror',
    url: 'https://blog.codinghorror.com',
    feedUrl: 'https://feeds.feedburner.com/codinghorror',
    description: 'Jeff Atwood on software craftsmanship, developer culture, and the human side of code.',
    tags: ['dev'],
    quality: 2,
  },
  {
    label: 'Dan Abramov (Overreacted)',
    url: 'https://overreacted.io',
    feedUrl: 'https://overreacted.io/rss.xml',
    description: 'Deep explorations of React internals and JavaScript mental models from the Redux creator.',
    tags: ['dev', 'web'],
    quality: 3,
  },
  {
    label: 'Jake Archibald',
    url: 'https://jakearchibald.com',
    feedUrl: 'https://jakearchibald.com/posts.rss',
    description: "Chrome developer advocate's precise articles on browser internals and web performance.",
    tags: ['web', 'dev'],
    quality: 3,
  },
  {
    label: 'CSS Weekly',
    url: 'https://css-weekly.com',
    feedUrl: 'https://feeds.feedburner.com/CSSWeekly',
    description: 'Tightly curated weekly digest of the most useful CSS articles and experiments.',
    tags: ['web', 'dev', 'design'],
    quality: 2,
  },
  {
    label: 'Frontend Focus',
    url: 'https://frontendfoc.us',
    feedUrl: 'https://frontendfoc.us/rss/1a1a0847',
    description: 'Weekly roundup of front-end news, specs, and browser compatibility updates.',
    tags: ['web', 'dev'],
    quality: 2,
  },
  {
    label: 'Tania Rascia',
    url: 'https://www.taniarascia.com',
    feedUrl: 'https://www.taniarascia.com/rss.xml',
    description: 'Exceptionally clear full-stack tutorials that make complex topics genuinely accessible.',
    tags: ['dev', 'web'],
    quality: 2,
  },

  // ─── AI / ML ─────────────────────────────────────────────────────────────
  {
    label: 'OpenAI Blog',
    url: 'https://openai.com/blog',
    feedUrl: 'https://openai.com/blog/rss.xml',
    description: 'Primary announcements and research breakdowns from the GPT and DALL-E maker.',
    tags: ['ai', 'tech'],
    quality: 3,
  },
  {
    label: 'Anthropic News',
    url: 'https://www.anthropic.com/news',
    feedUrl: 'https://www.anthropic.com/rss.xml',
    description: 'Claude releases, safety research, and AI policy positions from Anthropic.',
    tags: ['ai', 'tech'],
    quality: 3,
  },
  {
    label: 'Google AI Blog',
    url: 'https://ai.googleblog.com',
    feedUrl: 'https://blog.research.google/feeds/posts/default',
    description: 'Research publications and product AI from the largest ML organization in the world.',
    tags: ['ai', 'tech'],
    quality: 3,
  },
  {
    label: 'DeepMind Blog',
    url: 'https://deepmind.google/discover/blog/',
    feedUrl: 'https://deepmind.google/blog/rss.xml',
    description: 'AlphaFold, Gemini, and frontier AI research from Google DeepMind.',
    tags: ['ai', 'science'],
    quality: 3,
  },
  {
    label: 'Hugging Face Blog',
    url: 'https://huggingface.co/blog',
    feedUrl: 'https://huggingface.co/blog/feed.xml',
    description: 'Open-source model releases, fine-tuning guides, and ML ecosystem news.',
    tags: ['ai', 'oss', 'dev'],
    quality: 3,
  },
  {
    label: 'fast.ai',
    url: 'https://www.fast.ai',
    feedUrl: 'https://www.fast.ai/index.xml',
    description: "Jeremy Howard's democratized take on deep learning — opinionated, practical, and free.",
    tags: ['ai', 'dev'],
    quality: 3,
  },
  {
    label: 'Towards Data Science',
    url: 'https://towardsdatascience.com',
    feedUrl: 'https://towardsdatascience.com/feed',
    description: 'High-volume Medium publication with practitioner-authored ML and data engineering articles.',
    tags: ['ai', 'dev'],
    quality: 2,
  },
  {
    label: 'The Gradient',
    url: 'https://thegradient.pub',
    feedUrl: 'https://thegradient.pub/rss/',
    description: 'Rigorous long-form AI research commentary written by PhD students and researchers.',
    tags: ['ai', 'science'],
    quality: 3,
  },
  {
    label: 'Import AI',
    url: 'https://jack-clark.net',
    feedUrl: 'https://jack-clark.net/feed/',
    description: "Jack Clark's sharp weekly digest of the most consequential AI research and policy news.",
    tags: ['ai', 'news'],
    quality: 3,
  },
  {
    label: 'The Batch (deeplearning.ai)',
    url: 'https://www.deeplearning.ai/the-batch/',
    feedUrl: 'https://www.deeplearning.ai/the-batch/feed/',
    description: "Andrew Ng's weekly AI newsletter connecting research papers to real-world impact.",
    tags: ['ai'],
    quality: 2,
  },
  {
    label: 'Papers With Code',
    url: 'https://paperswithcode.com',
    feedUrl: 'https://paperswithcode.com/rss.xml',
    description: 'ML papers ranked by GitHub stars — the fastest way to track what research is getting reproduced.',
    tags: ['ai', 'dev'],
    quality: 3,
  },
  {
    label: 'Simon Willison',
    url: 'https://simonwillison.net',
    feedUrl: 'https://simonwillison.net/atom/everything/',
    description: 'The most thorough practitioner log on LLMs, AI tooling, and web development experiments.',
    tags: ['ai', 'dev', 'web'],
    quality: 3,
  },
  {
    label: 'Ahead of AI',
    url: 'https://magazine.sebastianraschka.com',
    feedUrl: 'https://magazine.sebastianraschka.com/feed',
    description: 'Sebastian Raschka on LLM research, training techniques, and model benchmarks for practitioners.',
    tags: ['ai', 'dev'],
    quality: 3,
  },
  {
    label: 'AI Alignment Forum',
    url: 'https://www.alignmentforum.org',
    feedUrl: 'https://www.alignmentforum.org/feed.xml',
    description: 'Technical safety research and philosophical arguments about aligning powerful AI systems.',
    tags: ['ai'],
    quality: 2,
  },
  {
    label: 'LessWrong',
    url: 'https://www.lesswrong.com',
    feedUrl: 'https://www.lesswrong.com/feed.xml',
    description: 'Rationality and AI risk discussion — dense, rigorous, and occasionally prescient.',
    tags: ['ai', 'tech'],
    quality: 2,
  },
  {
    label: 'Andrej Karpathy',
    url: 'https://karpathy.github.io',
    feedUrl: 'https://karpathy.github.io/feed.xml',
    description: "Rare but landmark posts on neural networks and AI education from Tesla's former AI lead.",
    tags: ['ai', 'dev'],
    quality: 3,
  },
  {
    label: 'Stability AI Blog',
    url: 'https://stability.ai/blog',
    feedUrl: 'https://stability.ai/blog/rss',
    description: 'Stable Diffusion releases, open generative model research, and multimodal AI.',
    tags: ['ai', 'oss'],
    quality: 2,
  },
  {
    label: 'ML News (Yannic Kilcher)',
    url: 'https://www.youtube.com/@YannicKilcher',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew',
    description: 'Yannic Kilcher paper walkthroughs — the gold standard for understanding cutting-edge ML research.',
    tags: ['ai', 'youtube'],
    quality: 3,
  },
  {
    label: 'Two Minute Papers',
    url: 'https://www.youtube.com/@TwoMinutePapers',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg',
    description: 'Enthusiastic 2-minute video summaries of the most visually impressive AI research papers.',
    tags: ['ai', 'youtube'],
    quality: 2,
  },
  {
    label: 'Lex Fridman',
    url: 'https://www.youtube.com/@lexfridman',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA',
    description: 'Long-form interviews with AI researchers, scientists, and tech founders.',
    tags: ['ai', 'tech', 'youtube'],
    quality: 2,
  },
  {
    label: 'EleutherAI Blog',
    url: 'https://blog.eleuther.ai',
    feedUrl: 'https://blog.eleuther.ai/index.xml',
    description: 'Open-source LLM research, interpretability work, and evaluation from the Pile creators.',
    tags: ['ai', 'oss'],
    quality: 2,
  },
  {
    label: 'BAIR Blog',
    url: 'https://bair.berkeley.edu/blog',
    feedUrl: 'https://bair.berkeley.edu/blog/feed.xml',
    description: 'Berkeley AI Research on robotics, RL, NLP, and computer vision — academically rigorous.',
    tags: ['ai', 'science'],
    quality: 3,
  },
  {
    label: 'Microsoft Research Blog',
    url: 'https://www.microsoft.com/en-us/research/blog/',
    feedUrl: 'https://www.microsoft.com/en-us/research/feed/',
    description: 'Applied research from MSR on AI, quantum computing, and mixed reality.',
    tags: ['ai', 'tech'],
    quality: 2,
  },
  {
    label: 'MIT CSAIL News',
    url: 'https://www.csail.mit.edu/news',
    feedUrl: 'https://www.csail.mit.edu/rss/news',
    description: 'CS and AI research announcements from the world-leading MIT computer science lab.',
    tags: ['ai', 'science', 'tech'],
    quality: 2,
  },
  {
    label: 'Distill.pub',
    url: 'https://distill.pub',
    feedUrl: 'https://distill.pub/rss.xml',
    description: 'Interactive, beautifully designed ML explainers that set the bar for scientific communication.',
    tags: ['ai', 'science'],
    quality: 3,
  },

  // ─── DESIGN / UX ─────────────────────────────────────────────────────────
  {
    label: 'A List Apart',
    url: 'https://alistapart.com',
    feedUrl: 'https://alistapart.com/main/feed/',
    description: 'Foundational essays on web design, standards, and the culture of building for the web.',
    tags: ['design', 'web'],
    quality: 3,
  },
  {
    label: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com',
    feedUrl: 'https://www.nngroup.com/feed/rss/',
    description: 'Evidence-based UX research and usability guidelines from the industry authority.',
    tags: ['design', 'web'],
    quality: 3,
  },
  {
    label: 'UX Collective',
    url: 'https://uxdesign.cc',
    feedUrl: 'https://uxdesign.cc/feed',
    description: 'Curated UX articles from practitioners — strong on research methods and case studies.',
    tags: ['design'],
    quality: 2,
  },
  {
    label: 'Figma Blog',
    url: 'https://www.figma.com/blog',
    feedUrl: 'https://www.figma.com/blog/rss.xml',
    description: 'Design systems, collaborative workflow research, and product updates from Figma.',
    tags: ['design', 'dev'],
    quality: 2,
  },
  {
    label: 'Dribbble Blog',
    url: 'https://dribbble.com/stories',
    feedUrl: 'https://dribbble.com/stories/posts.rss',
    description: 'Visual design trends, designer interviews, and career advice from the design community.',
    tags: ['design'],
    quality: 1,
  },
  {
    label: 'Creative Bloq',
    url: 'https://www.creativebloq.com',
    feedUrl: 'https://www.creativebloq.com/feed',
    description: 'Graphic design, illustration, and web design inspiration with practical tutorials.',
    tags: ['design', 'web'],
    quality: 1,
  },
  {
    label: 'iA Blog',
    url: 'https://ia.net/topics',
    feedUrl: 'https://ia.net/feed',
    description: 'Information Architecture on writing, typography, and software design with a philosophical edge.',
    tags: ['design', 'writing'],
    quality: 3,
  },
  {
    label: 'Frank Chimero',
    url: 'https://frankchimero.com',
    feedUrl: 'https://frankchimero.com/feed.xml',
    description: "Thoughtful essays on graphic design, making things on the web, and what good craft means.",
    tags: ['design', 'writing'],
    quality: 3,
  },
  {
    label: 'Design Systems Weekly',
    url: 'https://news.design.systems',
    feedUrl: 'https://news.design.systems/feed.rss',
    description: 'Weekly curation of design system news, new component libraries, and pattern documentation.',
    tags: ['design', 'dev'],
    quality: 2,
  },
  {
    label: 'UX Planet',
    url: 'https://uxplanet.org',
    feedUrl: 'https://uxplanet.org/feed',
    description: 'One-stop resource for UX best practices, prototyping guides, and accessibility how-tos.',
    tags: ['design'],
    quality: 1,
  },
  {
    label: 'Stéphanie Walter',
    url: 'https://stephaniewalter.design/blog/',
    feedUrl: 'https://stephaniewalter.design/feed/',
    description: 'High-quality UX research, mobile design, and conference presentation resources.',
    tags: ['design', 'web'],
    quality: 2,
  },
  {
    label: 'Design Details',
    url: 'https://designdetails.fm',
    feedUrl: 'https://feeds.simplecast.com/GpQaRkWr',
    description: 'Product design podcast dissecting the small decisions that make great apps feel right.',
    tags: ['design'],
    quality: 2,
  },
  {
    label: 'Muzli Design Inspiration',
    url: 'https://muz.li',
    feedUrl: 'https://muz.li/feed/',
    description: 'Daily curated visual design inspiration from across the web — quick dopamine for designers.',
    tags: ['design'],
    quality: 1,
  },

  // ─── SCIENCE ─────────────────────────────────────────────────────────────
  {
    label: 'NASA Breaking News',
    url: 'https://www.nasa.gov',
    feedUrl: 'https://www.nasa.gov/rss/dyn/breaking_news.rss',
    description: 'Official NASA mission updates, research discoveries, and space exploration news.',
    tags: ['space', 'science', 'news'],
    quality: 3,
  },
  {
    label: 'ESA News',
    url: 'https://www.esa.int',
    feedUrl: 'https://www.esa.int/rssfeed/Our_Activities/Space_Science',
    description: "European Space Agency's science mission results, satellite launches, and discoveries.",
    tags: ['space', 'science'],
    quality: 3,
  },
  {
    label: 'Nature News',
    url: 'https://www.nature.com/news',
    feedUrl: 'https://www.nature.com/nature.rss',
    description: 'The most-cited scientific journal covering breakthrough research across all disciplines.',
    tags: ['science'],
    quality: 3,
  },
  {
    label: 'Science Daily',
    url: 'https://www.sciencedaily.com',
    feedUrl: 'https://www.sciencedaily.com/rss/all.xml',
    description: 'High-volume aggregator of press releases from universities and research institutions.',
    tags: ['science', 'health'],
    quality: 1,
  },
  {
    label: 'Quanta Magazine',
    url: 'https://www.quantamagazine.org',
    feedUrl: 'https://www.quantamagazine.org/feed/',
    description: 'The best science journalism on the internet — physics, math, and biology made gripping.',
    tags: ['science', 'ai'],
    quality: 3,
  },
  {
    label: 'New Scientist',
    url: 'https://www.newscientist.com',
    feedUrl: 'https://www.newscientist.com/feed/home/',
    description: 'Weekly science magazine with strong editorial voice covering everything from cosmology to climate.',
    tags: ['science', 'news'],
    quality: 2,
  },
  {
    label: 'Scientific American',
    url: 'https://www.scientificamerican.com',
    feedUrl: 'https://rss.sciam.com/ScientificAmerican-Global',
    description: 'Accessible long-form science journalism for an educated general audience since 1845.',
    tags: ['science', 'health'],
    quality: 2,
  },
  {
    label: 'Ars Technica Science',
    url: 'https://arstechnica.com/science/',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/science',
    description: 'Peer-reviewed science reported with technical depth and appropriate skepticism.',
    tags: ['science', 'tech'],
    quality: 3,
  },
  {
    label: 'CERN News',
    url: 'https://home.cern/news',
    feedUrl: 'https://home.cern/api/news/news/rss.xml',
    description: 'Particle physics discoveries and accelerator updates directly from CERN.',
    tags: ['science'],
    quality: 2,
  },
  {
    label: 'arXiv CS New Submissions',
    url: 'https://arxiv.org',
    feedUrl: 'https://rss.arxiv.org/rss/cs.LG',
    description: 'Raw firehose of new machine learning preprints — unfiltered research before peer review.',
    tags: ['ai', 'science'],
    quality: 2,
  },
  {
    label: 'Physics Today',
    url: 'https://physicstoday.scitation.org',
    feedUrl: 'https://physicstoday.scitation.org/action/showFeed?type=etoc&feed=rss&jc=pto',
    description: 'The flagship magazine of the American Institute of Physics — accessible to specialists.',
    tags: ['science'],
    quality: 2,
  },
  {
    label: 'The Atlantic Science',
    url: 'https://www.theatlantic.com/science/',
    feedUrl: 'https://www.theatlantic.com/feed/channel/science/',
    description: 'Narrative science journalism that makes research feel urgent and human.',
    tags: ['science', 'news'],
    quality: 3,
  },
  {
    label: 'Eos (AGU)',
    url: 'https://eos.org',
    feedUrl: 'https://eos.org/feed',
    description: 'Earth and space science news from the American Geophysical Union — climate, oceans, geology.',
    tags: ['science', 'space'],
    quality: 2,
  },

  // ─── SECURITY ─────────────────────────────────────────────────────────────
  {
    label: 'Krebs on Security',
    url: 'https://krebsonsecurity.com',
    feedUrl: 'https://krebsonsecurity.com/feed/',
    description: "Brian Krebs's deep investigative reporting on cybercrime, breaches, and the fraud economy.",
    tags: ['security', 'news'],
    quality: 3,
  },
  {
    label: 'Schneier on Security',
    url: 'https://www.schneier.com',
    feedUrl: 'https://www.schneier.com/feed/atom/',
    description: 'Bruce Schneier on cryptography, surveillance, policy, and the sociology of security.',
    tags: ['security', 'tech'],
    quality: 3,
  },
  {
    label: 'The Hacker News',
    url: 'https://thehackernews.com',
    feedUrl: 'https://feeds.feedburner.com/TheHackersNews',
    description: 'High-volume breaking news on vulnerabilities, breaches, and threat intelligence.',
    tags: ['security', 'news'],
    quality: 2,
  },
  {
    label: 'Dark Reading',
    url: 'https://www.darkreading.com',
    feedUrl: 'https://www.darkreading.com/rss.xml',
    description: 'Enterprise security news covering threat research, cloud risk, and compliance.',
    tags: ['security', 'tech'],
    quality: 2,
  },
  {
    label: 'SANS Internet Stormcast',
    url: 'https://isc.sans.edu',
    feedUrl: 'https://isc.sans.edu/rssfeed_full.xml',
    description: 'Daily five-minute podcast and diary on active internet threats and new CVEs.',
    tags: ['security'],
    quality: 2,
  },
  {
    label: 'Google Project Zero',
    url: 'https://googleprojectzero.blogspot.com',
    feedUrl: 'https://googleprojectzero.blogspot.com/feeds/posts/default',
    description: 'State-of-the-art vulnerability research and zero-day disclosures from Google.',
    tags: ['security', 'dev'],
    quality: 3,
  },
  {
    label: 'PortSwigger Research',
    url: 'https://portswigger.net/research',
    feedUrl: 'https://portswigger.net/research/rss',
    description: 'Web application security research from the Burp Suite makers — novel attack techniques.',
    tags: ['security', 'web'],
    quality: 3,
  },
  {
    label: 'Malwarebytes Labs',
    url: 'https://www.malwarebytes.com/blog',
    feedUrl: 'https://www.malwarebytes.com/blog/feed/',
    description: 'Malware analysis, threat actor reports, and consumer security news.',
    tags: ['security'],
    quality: 2,
  },
  {
    label: 'Cloudflare Security Blog',
    url: 'https://blog.cloudflare.com/tag/security/',
    feedUrl: 'https://blog.cloudflare.com/tag/security/rss/',
    description: 'DDoS post-mortems, BGP hijack analyses, and cryptographic protocol work from Cloudflare.',
    tags: ['security', 'tech'],
    quality: 3,
  },
  {
    label: 'BleepingComputer',
    url: 'https://www.bleepingcomputer.com',
    feedUrl: 'https://www.bleepingcomputer.com/feed/',
    description: 'Fastest breaking coverage of ransomware attacks, malware campaigns, and data breaches.',
    tags: ['security', 'news'],
    quality: 2,
  },
  {
    label: 'NIST Cybersecurity Insights',
    url: 'https://www.nist.gov/blogs/cybersecurity-insights',
    feedUrl: 'https://www.nist.gov/blogs/cybersecurity-insights/rss.xml',
    description: 'Standards-body guidance on frameworks, zero trust, and emerging cybersecurity practices.',
    tags: ['security'],
    quality: 2,
  },

  // ─── LINUX / OSS ─────────────────────────────────────────────────────────
  {
    label: 'LWN.net',
    url: 'https://lwn.net',
    feedUrl: 'https://lwn.net/headlines/rss',
    description: 'The deepest and most reliable source for Linux kernel and open-source software news.',
    tags: ['linux', 'oss', 'dev'],
    quality: 3,
  },
  {
    label: 'Phoronix',
    url: 'https://www.phoronix.com',
    feedUrl: 'https://www.phoronix.com/rss.php',
    description: 'Linux hardware benchmarks, driver releases, and kernel patch coverage — obsessive detail.',
    tags: ['linux', 'tech'],
    quality: 2,
  },
  {
    label: "It's FOSS",
    url: 'https://itsfoss.com',
    feedUrl: 'https://itsfoss.com/feed/',
    description: 'Beginner-friendly Linux tutorials, distro news, and open-source software reviews.',
    tags: ['linux', 'oss'],
    quality: 1,
  },
  {
    label: 'OMG! Ubuntu',
    url: 'https://www.omgubuntu.co.uk',
    feedUrl: 'https://www.omgubuntu.co.uk/feed',
    description: 'Ubuntu and GNOME news with fast, friendly coverage of the mainstream Linux desktop.',
    tags: ['linux'],
    quality: 1,
  },
  {
    label: 'Fedora Magazine',
    url: 'https://fedoramagazine.org',
    feedUrl: 'https://fedoramagazine.org/feed/',
    description: 'Official Fedora blog with release notes, how-to guides, and community spotlights.',
    tags: ['linux', 'oss'],
    quality: 1,
  },
  {
    label: 'Ubuntu Blog',
    url: 'https://ubuntu.com/blog',
    feedUrl: 'https://ubuntu.com/blog/feed',
    description: 'Canonical engineering updates, enterprise Ubuntu news, and cloud/IoT announcements.',
    tags: ['linux', 'tech'],
    quality: 2,
  },
  {
    label: 'GNOME News',
    url: 'https://www.gnome.org/news/',
    feedUrl: 'https://www.gnome.org/news/feed/',
    description: 'GNOME desktop release announcements, design changes, and foundation news.',
    tags: ['linux', 'oss', 'design'],
    quality: 1,
  },
  {
    label: 'KDE Planet',
    url: 'https://planet.kde.org',
    feedUrl: 'https://planet.kde.org/rss20.xml',
    description: 'Aggregated developer blogs from across the KDE community — technical and personal.',
    tags: ['linux', 'oss'],
    quality: 1,
  },
  {
    label: 'FreeBSD News',
    url: 'https://www.freebsd.org/news/',
    feedUrl: 'https://www.freebsd.org/news/rss.xml',
    description: 'Official FreeBSD release announcements and security advisories.',
    tags: ['linux', 'oss', 'security'],
    quality: 2,
  },
  {
    label: 'Debian News',
    url: 'https://www.debian.org/News/',
    feedUrl: 'https://www.debian.org/News/news',
    description: 'Official release and security announcements from the oldest major Linux distribution.',
    tags: ['linux', 'oss'],
    quality: 2,
  },
  {
    label: 'Tails Blog',
    url: 'https://tails.net/news/',
    feedUrl: 'https://tails.net/news/index.en.rss',
    description: 'Security and privacy-focused OS release notes and threat disclosures.',
    tags: ['linux', 'security', 'oss'],
    quality: 2,
  },
  {
    label: 'Linux Journal',
    url: 'https://www.linuxjournal.com',
    feedUrl: 'https://www.linuxjournal.com/node/feed',
    description: 'Long-running publication for Linux professionals — tutorials, command-line tricks, and commentary.',
    tags: ['linux', 'dev'],
    quality: 1,
  },

  // ─── BUSINESS / FINANCE ──────────────────────────────────────────────────
  {
    label: 'Benedict Evans',
    url: 'https://www.ben-evans.com',
    feedUrl: 'https://www.ben-evans.com/benedictevans/rss.xml',
    description: 'The sharpest long-form analysis on tech industry structure, media, and platform economics.',
    tags: ['business', 'tech'],
    quality: 3,
  },
  {
    label: 'Stratechery',
    url: 'https://stratechery.com',
    feedUrl: 'https://stratechery.com/feed/',
    description: "Ben Thompson's daily aggregation framework for understanding tech strategy and market power.",
    tags: ['business', 'tech'],
    quality: 3,
  },
  {
    label: 'Not Boring',
    url: 'https://www.notboring.co',
    feedUrl: 'https://www.notboring.co/feed',
    description: 'Packy McCormick on ambitious companies, strategy, and how compelling narratives drive capital.',
    tags: ['business', 'finance'],
    quality: 2,
  },
  {
    label: 'Morning Brew',
    url: 'https://www.morningbrew.com',
    feedUrl: 'https://www.morningbrew.com/daily/issues.rss',
    description: 'Snappy daily business news digest that respects your time.',
    tags: ['business', 'news', 'finance'],
    quality: 1,
  },
  {
    label: 'Axios',
    url: 'https://www.axios.com',
    feedUrl: 'https://api.axios.com/feed/',
    description: 'Smart brevity format for business, tech, and politics — maximum signal per word.',
    tags: ['news', 'business', 'tech'],
    quality: 2,
  },
  {
    label: 'Quartz',
    url: 'https://qz.com',
    feedUrl: 'https://cms.qz.com/feed/',
    description: 'Global business journalism with strong emerging markets and technology angles.',
    tags: ['business', 'news'],
    quality: 2,
  },
  {
    label: 'Bloomberg Technology',
    url: 'https://www.bloomberg.com/technology',
    feedUrl: 'https://feeds.bloomberg.com/technology/news.rss',
    description: 'Financial and enterprise tech reporting with access to executives other outlets lack.',
    tags: ['business', 'tech', 'finance'],
    quality: 3,
  },
  {
    label: 'CB Insights',
    url: 'https://www.cbinsights.com/research',
    feedUrl: 'https://www.cbinsights.com/research/feed/',
    description: 'Venture data and market maps tracking startup funding, exits, and emerging industry trends.',
    tags: ['business', 'finance'],
    quality: 2,
  },
  {
    label: 'Y Combinator Blog',
    url: 'https://www.ycombinator.com/blog',
    feedUrl: 'https://www.ycombinator.com/blog/rss/',
    description: 'Startup advice, batch announcements, and research from the most important accelerator.',
    tags: ['business', 'tech'],
    quality: 2,
  },
  {
    label: 'First Round Review',
    url: 'https://review.firstround.com',
    feedUrl: 'https://review.firstround.com/feed.xml',
    description: 'In-depth playbooks from founders and operators on building high-performance startups.',
    tags: ['business'],
    quality: 3,
  },
  {
    label: 'Both Sides of the Table',
    url: 'https://bothsidesofthetable.com',
    feedUrl: 'https://bothsidesofthetable.com/feed',
    description: 'Mark Suster on VC mechanics, fundraising, and company building from both investor and founder views.',
    tags: ['business', 'finance'],
    quality: 2,
  },
  {
    label: 'AVC (Fred Wilson)',
    url: 'https://avc.com',
    feedUrl: 'https://avc.com/feed/',
    description: "Union Square Ventures' Fred Wilson on venture capital, crypto, and technology investing.",
    tags: ['business', 'finance', 'crypto'],
    quality: 2,
  },
  {
    label: 'The Information',
    url: 'https://www.theinformation.com',
    feedUrl: 'https://www.theinformation.com/feed',
    description: 'Subscriber-funded tech journalism that breaks stories before the rest of the press.',
    tags: ['business', 'tech', 'news'],
    quality: 3,
  },
  {
    label: 'A16Z Blog',
    url: 'https://a16z.com',
    feedUrl: 'https://a16z.com/feed/',
    description: 'Andreessen Horowitz on AI, crypto, bio, and the macro thesis behind their investment portfolio.',
    tags: ['business', 'finance', 'tech'],
    quality: 2,
  },

  // ─── GAMING ──────────────────────────────────────────────────────────────
  {
    label: 'Kotaku',
    url: 'https://kotaku.com',
    feedUrl: 'https://kotaku.com/rss',
    description: 'Games culture journalism — industry criticism, leaked news, and labor coverage.',
    tags: ['gaming', 'news'],
    quality: 2,
  },
  {
    label: 'Rock Paper Shotgun',
    url: 'https://www.rockpapershotgun.com',
    feedUrl: 'https://www.rockpapershotgun.com/feed/news',
    description: 'PC gaming news and reviews with a distinctive editorial voice and genuine love of games.',
    tags: ['gaming'],
    quality: 2,
  },
  {
    label: 'Eurogamer',
    url: 'https://www.eurogamer.net',
    feedUrl: 'https://www.eurogamer.net/?format=rss',
    description: 'European perspective on games news, reviews, and digital foundry hardware analysis.',
    tags: ['gaming'],
    quality: 2,
  },
  {
    label: 'Polygon',
    url: 'https://www.polygon.com',
    feedUrl: 'https://www.polygon.com/rss/index.xml',
    description: 'Games journalism with strong entertainment and pop culture angles.',
    tags: ['gaming', 'news'],
    quality: 2,
  },
  {
    label: 'PC Gamer',
    url: 'https://www.pcgamer.com',
    feedUrl: 'https://www.pcgamer.com/rss/',
    description: 'PC gaming reviews, hardware guides, and enthusiast coverage with a long legacy.',
    tags: ['gaming'],
    quality: 2,
  },
  {
    label: 'Game Developer (Gamasutra)',
    url: 'https://www.gamedeveloper.com',
    feedUrl: 'https://www.gamedeveloper.com/rss.xml',
    description: 'GDC post-mortems, game design theory, and industry news for professional developers.',
    tags: ['gaming', 'dev'],
    quality: 2,
  },
  {
    label: 'IGN',
    url: 'https://www.ign.com',
    feedUrl: 'https://feeds.ign.com/ign/all',
    description: 'Mainstream games and entertainment news with wide release coverage and video reviews.',
    tags: ['gaming', 'news'],
    quality: 1,
  },
  {
    label: 'The Verge Games',
    url: 'https://www.theverge.com/games',
    feedUrl: 'https://www.theverge.com/rss/games/index.xml',
    description: 'Tech-forward games coverage focusing on industry deals, platforms, and hardware.',
    tags: ['gaming', 'tech'],
    quality: 2,
  },
  {
    label: '80 Level',
    url: 'https://80.lv',
    feedUrl: 'https://80.lv/feed/',
    description: 'Game art breakdowns, Unreal/Unity tutorials, and 3D artist interviews for game devs.',
    tags: ['gaming', 'dev', 'design'],
    quality: 2,
  },

  // ─── SPACE ───────────────────────────────────────────────────────────────
  {
    label: 'NASA JPL News',
    url: 'https://www.jpl.nasa.gov/news',
    feedUrl: 'https://www.jpl.nasa.gov/feeds/news',
    description: "Robotic mission updates — Mars rovers, Voyager telemetry, and JPL's deep space science.",
    tags: ['space', 'science'],
    quality: 3,
  },
  {
    label: 'SpaceFlightNow',
    url: 'https://spaceflightnow.com',
    feedUrl: 'https://spaceflightnow.com/feed/',
    description: 'Real-time launch coverage and orbital mission reporting with technical depth.',
    tags: ['space', 'news'],
    quality: 2,
  },
  {
    label: 'NASASpaceFlight',
    url: 'https://www.nasaspaceflight.com',
    feedUrl: 'https://www.nasaspaceflight.com/feed/',
    description: 'Community-run site with the most detailed Starship and commercial launch coverage anywhere.',
    tags: ['space', 'news'],
    quality: 3,
  },
  {
    label: 'Sky & Telescope',
    url: 'https://skyandtelescope.org',
    feedUrl: 'https://skyandtelescope.org/astronomy-news/feed/',
    description: 'Observational astronomy news and sky event calendars for amateur and professional astronomers.',
    tags: ['space', 'science'],
    quality: 2,
  },
  {
    label: 'The Planetary Society',
    url: 'https://www.planetary.org',
    feedUrl: 'https://www.planetary.org/articles.rss',
    description: 'Space advocacy, mission science, and planetary defense updates from Carl Sagan's org.',
    tags: ['space', 'science'],
    quality: 2,
  },
  {
    label: 'Spaceflight Insider',
    url: 'https://www.spaceflightinsider.com',
    feedUrl: 'https://www.spaceflightinsider.com/feed/',
    description: 'Detailed reporting on launch vehicles, satellite missions, and exploration milestones.',
    tags: ['space'],
    quality: 2,
  },
  {
    label: 'Universe Today',
    url: 'https://www.universetoday.com',
    feedUrl: 'https://www.universetoday.com/feed/',
    description: 'Daily astronomy and space science news accessible to enthusiasts without a PhD.',
    tags: ['space', 'science'],
    quality: 2,
  },
  {
    label: 'Space.com',
    url: 'https://www.space.com',
    feedUrl: 'https://www.space.com/feeds/all',
    description: 'Mainstream space news covering launches, discoveries, and astronomy for general audiences.',
    tags: ['space', 'news'],
    quality: 1,
  },
  {
    label: 'Astronomy Picture of the Day',
    url: 'https://apod.nasa.gov/apod/',
    feedUrl: 'https://apod.nasa.gov/apod.rss',
    description: 'A different NASA-curated space image every day with a brief expert explanation.',
    tags: ['space', 'science'],
    quality: 2,
  },

  // ─── HEALTH / SCIENCE ────────────────────────────────────────────────────
  {
    label: 'NIH News in Health',
    url: 'https://newsinhealth.nih.gov',
    feedUrl: 'https://newsinhealth.nih.gov/feeds/allnews.rss',
    description: 'Plain-language health and medical research summaries from the National Institutes of Health.',
    tags: ['health', 'science'],
    quality: 2,
  },
  {
    label: 'WHO News',
    url: 'https://www.who.int/news',
    feedUrl: 'https://www.who.int/feeds/entity/news/en/rss.xml',
    description: 'Global public health emergencies, disease outbreaks, and policy from the WHO.',
    tags: ['health', 'news'],
    quality: 2,
  },
  {
    label: 'Harvard Health Blog',
    url: 'https://www.health.harvard.edu/blog',
    feedUrl: 'https://www.health.harvard.edu/blog/feed',
    description: 'Evidence-based health advice from Harvard Medical School faculty — clinical and nuanced.',
    tags: ['health'],
    quality: 2,
  },
  {
    label: 'Science-Based Medicine',
    url: 'https://sciencebasedmedicine.org',
    feedUrl: 'https://sciencebasedmedicine.org/feed/',
    description: 'Rigorous critical appraisal of medical claims — the antidote to health misinformation.',
    tags: ['health', 'science'],
    quality: 3,
  },
  {
    label: 'Psychology Today',
    url: 'https://www.psychologytoday.com',
    feedUrl: 'https://www.psychologytoday.com/intl/front-page/feed',
    description: 'Behavioral science, mental health research, and therapy insights for a general readership.',
    tags: ['health'],
    quality: 1,
  },
  {
    label: 'STAT News',
    url: 'https://www.statnews.com',
    feedUrl: 'https://www.statnews.com/feed/',
    description: 'Serious health and biotech journalism covering pharma, clinical trials, and public health policy.',
    tags: ['health', 'science', 'business'],
    quality: 3,
  },
  {
    label: 'MedPage Today',
    url: 'https://www.medpagetoday.com',
    feedUrl: 'https://www.medpagetoday.com/rss/headlines.xml',
    description: 'Clinical trial results and medical practice news for healthcare professionals.',
    tags: ['health', 'science'],
    quality: 2,
  },
  {
    label: 'The BMJ',
    url: 'https://www.bmj.com',
    feedUrl: 'https://www.bmj.com/rss/current.xml',
    description: 'One of the world's oldest medical journals — peer-reviewed research and editorials.',
    tags: ['health', 'science'],
    quality: 3,
  },
  {
    label: 'Examine.com Blog',
    url: 'https://examine.com',
    feedUrl: 'https://examine.com/feed.xml',
    description: 'Evidence-based supplement and nutrition research summaries without commercial bias.',
    tags: ['health', 'science'],
    quality: 3,
  },

  // ─── YOUTUBE CHANNELS ────────────────────────────────────────────────────
  {
    label: 'Computerphile',
    url: 'https://www.youtube.com/@Computerphile',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA',
    description: 'University of Nottingham professors explain CS concepts — algorithms, cryptography, compilers.',
    tags: ['tech', 'dev', 'youtube'],
    quality: 3,
  },
  {
    label: 'Numberphile',
    url: 'https://www.youtube.com/@numberphile',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A',
    description: 'Mathematicians discuss fascinating numbers and theorems with contagious enthusiasm.',
    tags: ['science', 'youtube'],
    quality: 3,
  },
  {
    label: 'Veritasium',
    url: 'https://www.youtube.com/@veritasium',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA',
    description: 'Science videos that challenge intuition and explain phenomena most people never question.',
    tags: ['science', 'youtube'],
    quality: 3,
  },
  {
    label: '3Blue1Brown',
    url: 'https://www.youtube.com/@3blue1brown',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAg',
    description: 'The most beautiful math visualizations on the internet — linear algebra, calculus, and AI explained.',
    tags: ['science', 'ai', 'youtube'],
    quality: 3,
  },
  {
    label: 'Fireship',
    url: 'https://www.youtube.com/@Fireship',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA',
    description: '100-second tech explainers that are genuinely funny and accurate — essential developer content.',
    tags: ['dev', 'tech', 'youtube'],
    quality: 3,
  },
  {
    label: 'TechLinked',
    url: 'https://www.youtube.com/@TechLinked',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCeeFfhMcJa1kjtfZAGskOCA',
    description: 'Fast-paced tech news from the Linus Media Group team — irreverent and well-researched.',
    tags: ['tech', 'news', 'youtube'],
    quality: 2,
  },
  {
    label: 'Linus Tech Tips',
    url: 'https://www.youtube.com/@LinusTechTips',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCXuqSBlHAE6Xw-yeJA0Tunw',
    description: 'Consumer hardware reviews, PC builds, and data center adventures with high production quality.',
    tags: ['tech', 'youtube'],
    quality: 2,
  },
  {
    label: 'MKBHD',
    url: 'https://www.youtube.com/@mkbhd',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCBcRF18a7Qf58cCRy5xuWwQ',
    description: 'The gold standard for smartphone and gadget reviews — cinematic quality, measured opinions.',
    tags: ['tech', 'mobile', 'youtube'],
    quality: 2,
  },
  {
    label: 'The Coding Train',
    url: 'https://www.youtube.com/@TheCodingTrain',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCvjgXvBlbQiydffZU7m1_aw',
    description: 'Daniel Shiffman on creative coding, generative art, and machine learning with genuine joy.',
    tags: ['dev', 'ai', 'youtube'],
    quality: 2,
  },
  {
    label: 'George Hotz (geohot)',
    url: 'https://www.youtube.com/@geohotstreams',
    feedUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCwgKmJM4K5XcnCCkI5mMvMw',
    description: 'Live coding sessions on comma.ai, tinygrad, and adversarial AI from an iconic hacker.',
    tags: ['ai', 'dev', 'youtube'],
    quality: 2,
  },

  // ─── WRITING / PRODUCTIVITY ──────────────────────────────────────────────
  {
    label: 'Paul Graham (via RSS)',
    url: 'https://paulgraham.com',
    feedUrl: 'https://www.aaronsw.com/2002/feeds/pgessays.rss',
    description: 'Mirrors PG essays in a reliable feed — foundational thinking on startups and ideas.',
    tags: ['writing', 'business'],
    quality: 3,
  },
  {
    label: 'Brain Pickings (The Marginalian)',
    url: 'https://www.themarginalian.org',
    feedUrl: 'https://www.themarginalian.org/feed/',
    description: "Maria Popova's deep explorations of literature, philosophy, and the intersection of art and science.",
    tags: ['writing', 'science'],
    quality: 3,
  },
  {
    label: 'Cal Newport',
    url: 'https://calnewport.com/blog/',
    feedUrl: 'https://feeds.feedburner.com/StudyHacks',
    description: 'Deep work theory, digital minimalism, and focused career development from the Georgetown professor.',
    tags: ['productivity', 'writing'],
    quality: 2,
  },
  {
    label: 'Farnam Street',
    url: 'https://fs.blog',
    feedUrl: 'https://feeds.feedburner.com/68131',
    description: 'Mental models, decision-making frameworks, and curated wisdom from great thinkers.',
    tags: ['productivity', 'writing'],
    quality: 3,
  },
  {
    label: 'Wait But Why',
    url: 'https://waitbutwhy.com',
    feedUrl: 'https://waitbutwhy.com/feed',
    description: 'Massively long illustrated essays on existential topics — AI risk, procrastination, Elon Musk.',
    tags: ['writing', 'tech', 'ai'],
    quality: 3,
  },
  {
    label: 'Gwern.net',
    url: 'https://www.gwern.net',
    feedUrl: 'https://www.gwern.net/feed',
    description: 'Exhaustively researched long-form essays on statistics, AI, and psychology by a reclusive polymath.',
    tags: ['ai', 'science', 'writing'],
    quality: 3,
  },
  {
    label: 'Kottke.org',
    url: 'https://kottke.org',
    feedUrl: 'https://feeds.kottke.org/main',
    description: 'Jason Kottke curating the interesting web since 1998 — eclectic, curious, and reliably good.',
    tags: ['writing', 'tech'],
    quality: 2,
  },
  {
    label: 'Daring Fireball',
    url: 'https://daringfireball.net',
    feedUrl: 'https://daringfireball.net/feeds/main',
    description: "John Gruber's sharp Apple commentary and the original home of Markdown.",
    tags: ['tech', 'writing'],
    quality: 2,
  },
  {
    label: 'Ness Labs',
    url: 'https://nesslabs.com',
    feedUrl: 'https://nesslabs.com/feed',
    description: 'Mindful productivity and neuroscience-backed approaches to creative work and learning.',
    tags: ['productivity', 'health'],
    quality: 2,
  },

  // ─── CRYPTO / WEB3 ───────────────────────────────────────────────────────
  {
    label: 'Ethereum Foundation Blog',
    url: 'https://blog.ethereum.org',
    feedUrl: 'https://blog.ethereum.org/en/feed.xml',
    description: 'Protocol upgrades, research posts, and ecosystem news directly from the Ethereum Foundation.',
    tags: ['crypto', 'dev'],
    quality: 2,
  },
  {
    label: 'Vitalik Buterin',
    url: 'https://vitalik.eth.limo',
    feedUrl: 'https://vitalik.eth.limo/feed.xml',
    description: "Long essays from Ethereum's co-founder on cryptoeconomics, governance, and mechanism design.",
    tags: ['crypto', 'tech'],
    quality: 3,
  },
  {
    label: 'CoinDesk',
    url: 'https://www.coindesk.com',
    feedUrl: 'https://www.coindesk.com/arc/outboundfeeds/rss/',
    description: 'Crypto market news, regulatory developments, and blockchain technology coverage.',
    tags: ['crypto', 'finance', 'news'],
    quality: 1,
  },
  {
    label: 'Bankless',
    url: 'https://bankless.com',
    feedUrl: 'https://www.bankless.com/feed',
    description: 'DeFi strategy, Ethereum ecosystem deep-dives, and the crypto-native financial system thesis.',
    tags: ['crypto', 'finance'],
    quality: 2,
  },

  // ─── MOBILE ──────────────────────────────────────────────────────────────
  {
    label: 'Android Authority',
    url: 'https://www.androidauthority.com',
    feedUrl: 'https://www.androidauthority.com/feed/',
    description: 'Android news, phone reviews, and app coverage for enthusiasts and developers.',
    tags: ['mobile', 'tech'],
    quality: 1,
  },
  {
    label: '9to5Mac',
    url: 'https://9to5mac.com',
    feedUrl: 'https://9to5mac.com/feed/',
    description: 'Reliable Apple leaks and iOS/macOS coverage with good developer-facing posts.',
    tags: ['mobile', 'tech'],
    quality: 2,
  },
  {
    label: 'MacStories',
    url: 'https://www.macstories.net',
    feedUrl: 'https://www.macstories.net/feed/',
    description: 'Federico Viticci on iOS workflows, app design, and the Apple ecosystem — deeply opinionated.',
    tags: ['mobile', 'productivity', 'design'],
    quality: 2,
  },
];
